### ISSUE TITLE
Connection Reset Issuse

### ISSUE THREAD

**Issue by bahabryra** [just-classboard/just-classboard.github.io#4]
![Screenshot 2024-09-10 1 40 09 PM](https://github.com/user-attachments/assets/72ad0856-a300-4846-816a-3c84e2c05dbc)
We got A problem Boys
Its Constanly Showing this Error When Pge is loaded

**Comment by bahabryra** [comment]
I Think Its only on the device network (which is the same wifi for the whole VHCS)

**Comment by cobblesteve01** [comment]
yes, i am working on fixing it

**Comment by bahabryra** [comment]
great!! check yo mail also mr

**Comment by bahabryra** [comment]
Fixed Hopefully

**Comment by bahabryra** [comment]
FIxed Hopefully
